version: "3.8"
services:

  # Generates the JSON files at regular intervals by running the script using cron.
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    working_dir: /app
    restart: always
    volumes:
      - api-files:/app/output

volumes:
  api-files:
